[package]
name = "arti-chat-daemon-bin"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
arti-chat-daemon = { path = "../arti-chat-daemon" }
tokio = { version = "1.48.0", features = ["full"] }
tracing = "0.1.43"
tracing-subscriber = "0.3.22"
