[package]
name = "arti-chat-daemon"
version = "0.1.0"
edition = "2024"

[dependencies]
arti-client = "0.37.0"
futures = "0.3.31"
thiserror = "2.0.17"
tokio = "1.48.0"
tor-cell = "0.37.0"
tor-hsservice = "0.37.0"
tor-proto = "0.37.0"
tracing = "0.1.43"
tracing-subscriber = "0.3.22"
